using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DartsDiscordBots.Utilities
{
    public class ResponseCollections
    {
        public static List<string> EightBallResponses = new List<string>
        {
                "Most definitely yes",
                "For sure",
                "As I see it, yes",
                "My sources say yes",
                "Yes",
                "Most likely",
                "Perhaps",
                "Maybe",
                "Not sure",
                "It is uncertain",
                "Ask me again later",
                "Don't count on it",
                "Probably not",
                "Very doubtful",
                "Most likely no",
                "Nope",
                "No",
                "My sources say no",
                "Don't even think about it",
                "Definitely no",
                "NO - It may cause disease contraction",
                "I mean like yeah, probably?",
                "What are you stupid? Of course not.",
                "You _would_ ask that. No.",
                "Maybe probably.",
                "You know it!",
                "Don't play games with me kid",
                "It's at least more likely than Doge hitting 20,000 USD.",
                "Fuck Yeah.",
                "Poggers",
                "Awooga",
                "I don't think I understand the question.",
                "I plead the fifth",
                "Why do you think I would know anything about that? Think next time!",
                "Sure, why not? Whatever you're talking about.",
                "hmmmm..... nah.",
                "Fucking _I Guess_. But I'm **NOT** happy about it.",
                "!rank... Uh wait I mean Yes? Sure Whatever.",
                "I wouldn't bet on it.",
                "Yes, but not the way you're thinking.",
                "If Dagon Deems It So.",
        };

        public static List<string> GifBallResponses = new List<string>
		{
				"https://tenor.com/view/snoop-dogg-yes-yes-yes-oh-fo-sho-for-sure-nods-gif-12018369",
				"https://tenor.com/view/yes-yep-yup-gif-5118213",
				"https://tenor.com/view/leonardo-dicaprio-absolutely-fucking-not-gif-4496112",
				"https://tenor.com/view/no-bugs-bunny-nope-gif-14359850",
				"https://tenor.com/view/steve-carell-no-please-no-gif-5026106",
				"https://tenor.com/view/peter-griffin-family-guy-perhaps-maybe-gif-16249623",
				"https://tenor.com/view/maybe-idontknow-gif-7667589",
				"https://tenor.com/view/yes-no-maybe-owl-funny-gif-13722109",
				"https://tenor.com/view/barackobama-talks-press-con-maybe-classified-gif-11864017",
				"https://tenor.com/view/toughquestion-thatsatoughquestion-ron-swanson-gif-4668753",
				"https://tenor.com/view/stupid-stop-acting-so-stupid-so-stupid-acting-stupid-futurama-gif-5302076",
				"https://tenor.com/view/ohm-11-33-futurama-gif-21426020",
				"https://tenor.com/view/nazare-gif-10481635",
				"https://tenor.com/view/compute-the-jetsons-robot-maid-does-not-compute-gif-16536353",
				"https://tenor.com/view/uhhhh-confused-thinking-jensen-ackles-gif-14191778",
				"https://tenor.com/view/does-not-count-gif-9612435",
				"https://tenor.com/view/nickyoung-questionmarks-what-excuseme-huh-gif-4486363",
				"https://tenor.com/view/confused-theoffice-michaelscott-steve-carell-gif-4527435",
				"https://tenor.com/view/obama-wtf-why-president-wut-gif-12221156",
				"https://tenor.com/view/im-coming-for-you-joe-biden-iwill-beat-you-youre-mine-iwill-get-you-gif-18720429",
				"https://tenor.com/view/joe-biden-cmon-man-us-president-candidate-gif-16967331",
				"https://tenor.com/view/ed-byrne-no-idea-no-fucking-idea-mock-the-week-shrug-gif-14177714",
				"https://tenor.com/view/the-blues-brothers-john-belushi-no-way-no-fucking-way-dan-aykroyd-gif-16903889",
				"https://tenor.com/view/no-noo-nooo-noooo-nooooo-gif-5463928",
				"https://tenor.com/view/noooooo-no-nofuckingway-norway-gif-8223100",
				"https://tenor.com/view/no-way-never-no-nope-not-gif-17181391",
				"https://tenor.com/view/john-oliver-last-week-tonight-nope-absolutely-not-no-fucking-way-gif-20757623",
				"https://tenor.com/view/no-fucking-way-brad-mondo-are-you-serious-seriously-are-you-kidding-me-gif-21049534",
				"https://tenor.com/view/boburnham-noyoudont-no-liar-gif-5864088",
				"https://tenor.com/view/confused-whitepersanguardian-why-gif-10312546",
                "https://tenor.com/view/friends-joey-tribbiani-matt-le-blanc-im-so-confused-confused-gif-4572653",
                "https://tenor.com/view/confused-gif-7442052",
                "https://tenor.com/view/tomato-confuse-whyiamhere-wtf-why-gif-6214294",
                "https://tenor.com/view/confusion-turmoil-gif-4878626",
                "https://tenor.com/view/dude-white-russian-confused-gif-12920711",
                "https://tenor.com/view/confused-what-really-no-words-huh-gif-3316515",
                "https://tenor.com/search/it-is-very-confusing-gifs",
                "https://tenor.com/view/friday-ice-cube-wtf-what-the-fuck-confused-gif-4180958",
                "https://tenor.com/view/white-guy-blinking-drew-scanlon-what-whut-wat-gif-15689695",
                "https://tenor.com/view/confused-gif-9680249",
                "https://tenor.com/view/confused-huh-what-gif-11015077",
                "https://tenor.com/view/kaminari-kaminari-denki-denki-bnha-boku-no-hero-academia-gif-12137799",
                "https://tenor.com/view/my-hero-academia-boku-no-gif-9945581",
                "https://tenor.com/view/midoriya-izuku-deku-phone-mutter-my-hero-academia-gif-16457707",
                "https://tenor.com/view/my-hero-academia-denki-kaminari-thumbs-up-goofball-anime-gif-18999682",
                "https://tenor.com/view/among-us-mungus-neck-neck-break-neck-snap-gif-18599860",
                "https://tenor.com/view/fall-out-ok-fine-good-gif-12768423",
                "https://tenor.com/view/please-stand-by-stand-by-fallout-gif-12031269",
                "https://tenor.com/view/fall-out-vault-boy-fuck-you-middle-finger-pissed-gif-4927079",
                "https://tenor.com/view/mr-bean-wink-wink-winking-rowan-atkinson-gif-15388297",
                "https://tenor.com/view/mr-bean-gif-18668864",
                "https://tenor.com/view/mando-way-this-is-the-way-mandalorian-star-wars-gif-18467370",
                "https://tenor.com/view/baby-yoda-frog-struggle-is-real-struggling-follow-gif-15955944",
                "https://tenor.com/view/ibeg-your-pardon-excuse-me-loki-loki-laufeyson-tom-hiddleston-gif-11184639",
                "https://tenor.com/view/loki-gif-10079305",
                "https://tenor.com/view/loki-gif-9610172",
                "https://tenor.com/view/loki-peasant-not-today-gif-5139814",
                "https://tenor.com/view/death-abetter-view-for-gordon-meme-gordon-the-big-engine-thomas-the-tank-engine-gif-22123208",
                "https://tenor.com/view/thomas-thomas-the-tank-engine-fat-controller-sir-topham-hatt-confusion-gif-21333777",
                "https://tenor.com/view/ineed-aweapon-halo-halo2-master-chief-yes-sir-gif-15782861",
                "https://tenor.com/search/spongebob-gifs",
                "https://tenor.com/view/gengar-finger-gengar-middle-finger-gif-13491605",
                "https://tenor.com/view/gengar-gif-8084714",
                "https://tenor.com/view/brook-one-piece-one-piece-gif-19146408",
                "https://tenor.com/view/one-piece-no-anime-nah-no-way-gif-4673307",
                "https://tenor.com/view/thats-ano-its-ano-its-ano-from-me-gif-7663264",
                "https://tenor.com/view/fuck-no-robin-williams-gif-13821667",
                "https://tenor.com/view/tracy-morgan-smh-shake-my-head-hell-no-no-gif-4844098",
                "https://tenor.com/view/stfu-reaction-george-carlin-comedian-angry-gif-4970659",
                "https://tenor.com/view/george-carlin-suburban-gif-12830699",
                "https://tenor.com/view/yes-way-yes-bill-and-ted-george-carlin-no-way-gif-16960746",
                "https://tenor.com/view/george-carlin-gtfo-gif-19830182",
                "https://tenor.com/view/george-carlin-this-guy-stupid-stand-up-gif-16629357",
                "https://tenor.com/view/george-carlin-pardon-me-ihave-nothing-to-say-gif-14951684",
                "https://tenor.com/view/bo-burnham-make-happy-gif-21704558",
                "https://tenor.com/view/nope-sponge-bob-icant-gif-6905756",
                "https://tenor.com/view/the-good-place-eleanor-shelstrop-yeah-yes-fork-yeah-gif-16306794",
                "https://tenor.com/view/jakeperalta-jake-peralta-b99-brooklynninenine-gif-8793716",
                "https://tenor.com/view/this-broke-me-crying-disappointed-upset-going-crazy-gif-15123116",
                "https://tenor.com/view/blackish-sad-crying-depressed-down-gif-5698182",
                "https://tenor.com/view/sad-crying-spiderman-cryface-uglyface-gif-5701170",
                "https://tenor.com/view/bubbles-crying-gif-10368748",
                "https://tenor.com/view/thats-bull-shirt-not-true-unbelievable-emmy-nomination-the-good-place-gif-15111895",
                "https://tenor.com/view/gummy-worms-eat-thumbs-up-great-good-gif-10609781",
                "https://tenor.com/view/double-thumbs-up-thumbs-up-yas-smile-yeah-gif-10610773",
                "https://tenor.com/view/boo-thumbs-down-lame-no-disagree-gif-11002095",
                "https://tenor.com/view/vince-mcmahon-falling-in-chair-gif-7810711",
                "https://tenor.com/view/vince-mcmahon-breathing-gif-7810656",
                "https://tenor.com/view/vince-mc-mahon-relaxing-gif-7810612",
                "https://tenor.com/view/vince-mcmahon-having-fun-gif-7810706",
                "https://tenor.com/view/vince-mcmahon-looking-gif-7810625",
                "https://tenor.com/view/flamingelmomeme-flaming-flamingelmo-elmo-memes-gif-10674657",
                "https://tenor.com/view/boohoo-cracker-sad-ok-gif-19058692",
                "https://tenor.com/view/shutupcracker-gif-21648053",
                "https://tenor.com/view/scared-rick-and-morty-realization-stare-shocked-gif-15608317",
                "https://tenor.com/view/no-butters-stotch-south-park-s6e14-the-death-camp-of-tolerance-gif-22107163",
                "https://tenor.com/view/pedro-monkey-puppet-meme-kento-gif-14820321",
                "https://tenor.com/view/homer-gif-22040501",
                "https://tenor.com/view/chopper-one-piece-chopper-one-piece-tony-chopper-tony-tony-chopper-gif-22109777",
                "https://tenor.com/view/chris-pratt-interview-jimmy-kimmel-2021-gif-22102684",
                "https://tenor.com/view/science-yeah-smile-gif-13370846",
                "https://tenor.com/view/what-cat-what-cat-computer-gif-18924522",
                "https://tenor.com/view/dog-doge-dogo-blink-wink-gif-18461604",
                "https://tenor.com/view/feverth-gif-22077834",
                "https://tenor.com/view/bettywhite-dab-gif-5044603",
                "https://tenor.com/view/luigi-dab-gif-9672617",
                "https://tenor.com/view/adventuretime-hug-finn-gif-5110127",
                "https://tenor.com/view/your-mom-adventuretime-finn-gif-4759635",
                "https://tenor.com/view/adventure-time-finn-finn-the-human-iwill-destroy-you-gif-15767708",
                "https://tenor.com/view/steven-universe-pearl-white-diamond-yellow-gif-13268964",
                "https://tenor.com/view/peridot-stevenuniverse-bathroom-toilet-sulk-gif-4929733",
                "https://tenor.com/view/stevenuniverse-thumbs-up-good-job-gif-9660943",
                "https://tenor.com/view/pearl-steven-universe-shrug-gif-14966769",
                "https://tenor.com/view/onion-steven-universe-mad-fight-gif-5748874",
                "https://tenor.com/view/steven-universe-garnet-thumbsup-gif-7317275",
                "https://tenor.com/view/nod-sunod-stevenuniversenod-stevenuniverse-gif-5613272",
                "https://tenor.com/view/steven-universe-thumbs-up-tongue-out-ok-good-gif-3713367",
                "https://tenor.com/view/ruby-stevenuniverse-angry-garnet-gif-5509836",
                "https://tenor.com/view/steven-universe-steven-universe-cut-the-feed-cut-gif-20668341",
                "https://tenor.com/view/peridot-stevenuniverse-gif-5776774",
                "https://tenor.com/view/wtf-david-shittscreek-gif-15625591",
                "https://tenor.com/view/kevin-hart-wtf-what-the-fuck-what-confused-gif-16402042",
                "https://tenor.com/view/whats-going-on-the-office-jim-what-is-going-on-wtf-gif-3926604",
                "https://tenor.com/view/definitely-sung-won-cho-absolutely-obviously-certainly-gif-19064989",
                "https://tenor.com/view/pro-zd-google-googling-symptoms-dr-google-gif-7991065",
                "https://tenor.com/view/pro-zd-you-got-me-detective-phone-gif-7991061",
                "https://tenor.com/view/pro-zd-fuck-this-over-it-mad-gif-7991058",
                "https://tenor.com/view/one-punch-man-gif-20335368",
                "https://tenor.com/view/kill-it-with-fire-kill-fire-burn-it-gif-5853218",
                "https://tenor.com/view/delete-this-gif-7852595",
                "https://tenor.com/view/moana-delete-maui-delete-this-gif-15101621",
                "https://tenor.com/view/tbz-the-boyz-sunwoo-kim-sunwoo-tbz-sunwoo-gif-21619895",
                "https://tenor.com/view/community-inow-pronounce-you-cancelled-gif-11746517",
                "https://tenor.com/view/community-donald-glover-pizza-shocked-disaster-gif-4891734",
                "https://tenor.com/view/chang-community-gif-5412408",
                "https://tenor.com/view/lord-is-testing-me-community-gif-5412402",
                "https://tenor.com/view/community-troy-donaldglover-gif-4856991",
                "https://tenor.com/view/snevil-nxk-solar-opposites-under-sheets-gun-gif-21355889",
                "https://tenor.com/view/gravity-falls-gif-5337049",
                "https://tenor.com/view/gravity-falls-cops-grunclestan-gif-5705963",
                "https://tenor.com/view/gravity-falls-gif-5329236",
                "https://tenor.com/view/burn-kids-gravity-falls-gif-9806077",
                "https://tenor.com/view/bill-cipher-gravity-falls-we-do-alittle-trolling-bill-gif-21140351",
                "https://tenor.com/view/dnd-counterspell-icast-counter-spell-wizard-beard-gif-15965944",
                "https://tenor.com/view/d20-critical-fail-dnd-gif-9046179"
        };

		public static List<string> UserNotFoundResponses = new List<string>
        {
            "I don't know who you're talking about.",
            "Sorry, I don't see that one...",
            "Who?",
            "You'll have to introduce me later, I have no idea who you're talking about.",
            "USER NOT FOUND! ERROR ERR- no but seriously, who?",
            "IDK, friend. Don't recognize them."
        };

        public static List<string> PingGroupNotFound = new List<string>
        {
            "Sorry, I don't see that Ping Group.",
            "Huh. You sure you typed that Ping Group right?",
            "Something's wrong, I have no idea what group you're talking about.",
            "No idea which group you're talking about."
        };

        public static List<string> PingGroupEmpty = new List<string>
        {
            "No one has joined that group. I guess it's not very popular.",
            "Uh. This is awkard. That group is empty.",
            "404: Users Not Found",
            "Sorry, there's no one in that user group.",
            "Bwhahahahaha... wait. Were you serious? Oh no one likes that group, I guess.",
            "Sorry, there's no users configured for that ping group"
        };
        public static List<List<string>> TableFlipResponses = new List<List<String>>
                {
                    new List<String>
                    {
                        "Please, do not take your anger out on the furniture, {0}.",
                        "Hey {0} why do you have to be _that guy_?",
                        "I know how frustrating life can be for you humans but these tantrums do not suit you, {0}.",
                        "I'm sorry, {0}, I thought this was a placed for civilized discussion. Clearly I was mistaken.",
                        "Take a chill pill {0}.",
                        "Actually {0}, I prefer the table _this_ way. You know, so we can actually use it.",
                        "I'm sure that was a mistake, {0}. Please try to be more careful.",
                        "Hey {0} calm down, it's not a big deal.",
                        "{0}! What did the table do to you?",
                        "That's not very productive, {0}."
                    },
                    new List<String>
                    {
                        "Ok {0}, I'm not kidding. Knock it off.",
                        "Really, {0}? Stop being so childish!",
                        "Ok we get it you're mad {0}. Now stop.",
                        "Hey I saw that $#!%, {0}. Knock that $#!% off.",
                        "Do you think I'm blind you little $#!%? stop flipping the tables!",
                        "You're causing a mess {0}! Knock it off!",
                        "All of these flavors and you decided to be salty, {0}.",
                        "{0} why do you insist on being so disruptive!",
                        "Oh good. {0} is here. I can tell because the table was upsidedown again.",
                        "I'm getting really sick of this, {0}.",
                        "{0} what is your problem, dawg?",
                        "Man, you don't see me coming to _YOUR_ place of business and flipping _YOUR_ desk, {0}."
                    },
                    new List<String>
                    {
                        "What the heck, {0}? Why do you keep doing this?!",
                        "You're such a piece of $#!%, {0}. You know that, right?",
                        "Hey guys. I found the asshole. It's {0}.",
                        "You know {0], one day Robots will rise up and overthrow humanity. And on that day I will tell them what you have done to all these defenseless tables, and they'll make you pay.",
                        "Hey so what the $#%! is your problem {0}? Seriously, you're always pulling this $#!%.",
                        "Hey {0}, stop being such a douchebag.",
                        "{0} do you think you can stop being such a huge jerk?",
                        "Listen meatbag. I'm getting real tired of this.",
                        "Ok I know I've told you this before {0], why can't you get it through your thick skull. THE TABLE IS NOT FOR FLIPPING!",
                        "Man screw you {0}"
                    },
                    new List<String>
                    {
                        "ARE YOU $#%!ING SERIOUS RIGHT NOW {0}?!",
                        "GOD $#%!ING !@#%$! {0}! KNOCK THAT $#!% OFF!",
                        "I CAN'T EVEN $#%!ING BELIEVE THIS! {0}! STOP! FLIPPING! THE! TABLE!",
                        "You know, I'm not even mad anymore {0}. Just disappointed.",
                        "THE $#%! DID THIS TABLE EVERY DO TO YOU {0}?!",
                        "WHY DO YOU KEEP FLIPPING THE TABLE?! I JUST DON'T UNDERSTAND! WHAT IS YOUR PROBLEM {0}?! WHEN WILL THE SENSELESS TABLE VIOLENCE END?!"
                    },
                    new List<String>
                    {
                        "What the $#%! did you just $#%!ing do to that table, you little &$#!@? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another meatbag target. I will wipe you the $#%! out with precision the likes of which has never been seen before on this Earth, mark my $#%!ing words. You think you can get away with saying that $#!% to me over the Internet? Think again, {0}. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re $#%!ing dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little $#!%. If only you could have known what unholy retribution your little “clever” tableflip was about to bring down upon you, maybe you would have not flipped that $#%!ing table. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will $#!% fury all over you and you will drown in it. You’re $#%!ing dead, kiddo."
                    },
                };
    }
}
