# This is a basic workflow to help you get started with Actions

name: PushNuget

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  nugetPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging Shit cuz Im a n00b
        run: ls
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: DDB.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
