# This is a basic workflow to help you get started with Actions

name: PR-CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore DDB.sln
      - name: Build
        run: dotnet build --no-restore DDB.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal DDB.sln
